#page title
page_title                                : Pixel Buddy                               # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6451399345                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : http://bit.ly/pixel-buddy-beta            # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Pixel Buddy - color by number             # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : pixel art - paint by number

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Chunky Tofu Studios                               
your_link                                 : https://chunkytofustudios.com                     
your_city                                 : San Francisco & Princeton                                
email_address                             : chunkytofustudios@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : CntrArchetype
github_username                           : ChunkyTofuStudios
youtube_username                          : 
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Original handmade art
    description                           : Fun, colorful, unique pixel-art! We have simple, illustrative, or realistic artwork pieces you can pick from.
    fontawesome_icon_name                 : image
    
  - title                                 : Paint like Picasso
    description                           : The intuitive UI makes it super easy to paint art in minutes. Hold and drag to enter speed painting mode!
    fontawesome_icon_name                 : paint-brush
    
  - title                                 : Relax and decompress
    description                           : No stress painting. Paint while watching TV, or on the bus. Great way to relax and be creative.
    fontawesome_icon_name                 : couch
    
  - title                                 : Create your own
    description                           : Would you like to paint your dog? Or a dog in space? Just upload any picture and convert it to pixel art!
    fontawesome_icon_name                 : plus
    
  - title                                 : Safe and secure
    description                           : All artwork is curated in house, nothing inappropriate here. Plus your own paintings will always remain private.
    fontawesome_icon_name                 : user-shield
    
  - title                                 : iPhone and Android
    description                           : Regardless of which phone you have you can paint some pixels to relax.
    fontawesome_icon_name                 : mobile


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
